#ifndef KASHIERCOMMON_GLOBAL_H
#define KASHIERCOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KASHIERCOMMON_LIBRARY)
#  define KASHIERCOMMONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define KASHIERCOMMONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // KASHIERCOMMON_GLOBAL_H
