#ifndef EXPORT_H
#define EXPORT_H


#ifdef _BUILDING_KASHIER
#define KASHIER_DLL_EXPORT QX_DLL_EXPORT_HELPER
#else // _BUILDING_KASHIER
#define KASHIER_DLL_EXPORT QX_DLL_IMPORT_HELPER
#endif // _BUILDING_KASHIER

#ifdef _BUILDING_KASHIER
#define QX_REGISTER_HPP_KASHIER QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_KASHIER QX_REGISTER_CPP_EXPORT_DLL
#else // _BUILDING_KASHIER
#define QX_REGISTER_HPP_KASHIER QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_KASHIER QX_REGISTER_CPP_IMPORT_DLL
#endif // _BUILDING_KASHIER


#endif // EXPORT_H
